data:
  base:
    url:
     https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series

confirmed:
  data:
    url:
      ${data.base.url}/time_series_covid19_confirmed_global.csv
